### ISSUE TITLE
Error in compilation if folder name has spaces

### ISSUE THREAD

**Issue by sokrat-in-me** [totvs/advpl-vscode#269]
Bom dia, KillerAll! Greetings from Russia.
Thanks for this amazing tool. It is our favourite one!

I found an issue during a compilation. The AdvPL Bridge doesn't understand folder names with spaces. Could you fix it?
The log is presented below.

> Starting the compilation of the source:d:\git\ma3\Gestao de Suprimentos\Gestão de Compras\COMA010.PRX
> 
> Compilation started at Wed Sep 12 2018 16:29:01 GMT+0300 (Russia TZ 2 Standard Time)
> 
> Bridge Return:
> 
> SyntaxError: Unexpected end of JSON input
> Compilation finished at Wed Sep 12 2018 16:29:01 GMT+0300 (Russia TZ 2 Standard Time) Elapsed (0.155 secs.)

**Comment by killerall** [comment]
Hello,

I could not reproduce the problem.

```
Starting the compilation of the source:c:\Totvs\vscode\wk_lib_master\AdvplFramework\.workdir\Gestão de Compras\sera.prw

Compilation started at Wed Sep 12 2018 11:40:25 GMT-0300 (Hora oficial do Brasil)

Compilation finished successfully.
Compilation finished at Wed Sep 12 2018 11:40:28 GMT-0300 (Hora oficial do Brasil) Elapsed (2.303 secs.)

```


Please. enable logging on settings:

advpl.logger: true


In your user's temp folder (C:\Users\rodrigo.antonio\AppData\Local\Temp)
File:
AdvplDebugBridge.log

Post it here, please.

**Comment by killerall** [comment]
I don't understand what is happening.
There is a new version of AdvplDebugBride, which is used in linux and mac, and can be active in windows as well.
In the settings, activate:

"advpl.alpha_compile": true

It is necessary to generate the password Cipher again (it will be smaller than the current one).

See if it can compile, otherwise, see if it generates any log, with the name.

AdvplDebugGridC.log at the user's temp.

**Comment by killerall** [comment]
Corrigido e liberado na versão 0.14.2
