### ISSUE TITLE
Gerador de documentação

### ISSUE THREAD

**Issue by andradevictor** [totvs/advpl-vscode#94]
Bom dia,
   Gostaria de saber se existe algum atalho para geração de headerdoc igualmente o TDS faz apertando CTRL  SHIFT + D.

Grato!

**Comment by killerall** [comment]
Ola,
Da ctrl+space, comece escrever protheusdoc.

Vai gerar a doc.

//-------------------------------------------------------------------
/*/{Protheus.doc} function
description
@author  author
@since   date
@version version
/*/
//-------------------------------------------------------------------

Agora pegando das variaveis e nome automatico ainda não está disponivel.

**Comment by AlencarGabriel** [comment]
Olá @VctrAndrade , lancei recentemente uma extensão com o intuito de dar ao VsCode praticamente todos os recursos ProtheusDoc do TDS.

https://github.com/AlencarGabriel/ProtheusDoc-VsCode

**Comment by robsonrosilva** [comment]
Foi implementada essa funcionalidade na extensão do @AlencarGabriel  acredito que essa issue possa ser encerrada.
